export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL'

export const SENT_OTP_REQUEST = "SENT_OTP_REQUEST"
export const SENT_OTP_SUCCESS = "SENT_OTP_SUCCESS"
export const SENT_OTP_FAIL = "SENT_OTP_FAIL"

export const UPDATE_PASS_REQUEST = "UPDATE_PASS_REQUEST"
export const UPDATE_PASS_SUCCESS = "UPDATE_PASS_SUCCESS"
export const UPDATE_PASS_FAIL = "UPDATE_PASS_FAIL"


